CREATE DATABASE IF NOT EXISTS acm;
USE acm;

DROP TABLE IF EXISTS DESPESA;
DROP TABLE IF EXISTS CATEGORIA_DESPESA;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS SOCIO;
DROP TABLE IF EXISTS CONVENIO;
DROP TABLE IF EXISTS CONTA_PAGAMENTO;

CREATE TABLE `categoria_despesa` (
  `CD_ID` int(11) NOT NULL auto_increment,
  `CD_NOME` varchar(100) NOT NULL,
  PRIMARY KEY  (`CD_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=latin1;

CREATE TABLE `conta_pagamento` (
  `CP_ID` int(11) NOT NULL auto_increment,
  `CP_NOME` varchar(100) NOT NULL,
  `CP_CONTA` varchar(15) NOT NULL,
  `CP_AGENCIA` varchar(15) NOT NULL,
  `CP_BANCO` varchar(50) NOT NULL,
  PRIMARY KEY  (`CP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

CREATE TABLE `convenio` (
  `CON_ID` int(11) NOT NULL auto_increment,
  `CON_NOME` varchar(100) NOT NULL,
  `CON_PAGO_A_VISTA` varchar(3) NOT NULL,
  `CON_CONTA_PAGAMENTO` int(11) default NULL,
  `CON_DEPARTAMENTO` int(11) default NULL,
  `CON_SOCIO` bigint(20) default NULL,
  PRIMARY KEY  (`CON_ID`),
  KEY `FK_CONVENIO_DEPARTAMENTO` (`CON_DEPARTAMENTO`),
  KEY `FKCF178C31B9E7F93` (`CON_CONTA_PAGAMENTO`),
  CONSTRAINT `FKCF178C31B9E7F93` FOREIGN KEY (`CON_CONTA_PAGAMENTO`) REFERENCES `conta_pagamento` (`CP_ID`),
  CONSTRAINT `FK_CONVENIO_CONTA_PAGAMENTO` FOREIGN KEY (`CON_CONTA_PAGAMENTO`) REFERENCES `conta_pagamento` (`CP_ID`),
  CONSTRAINT `FK_CONVENIO_DEPARTAMENTO` FOREIGN KEY (`CON_DEPARTAMENTO`) REFERENCES `departamento` (`DEP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=latin1;

CREATE TABLE `departamento` (
  `DEP_ID` int(11) NOT NULL auto_increment,
  `DEP_NOME` varchar(100) NOT NULL,
  `DEP_SOCIO` int(11) default NULL,
  PRIMARY KEY  (`DEP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

CREATE TABLE `departamento_departamento` (
  `DD_ID` int(11) NOT NULL auto_increment,
  `DD_DEPARTAMENTO` int(11) NOT NULL,
  `DD_DEPARTAMENTO_DONO` int(11) NOT NULL,
  `DD_PORCENTAGEM` varchar(6) NOT NULL,
  PRIMARY KEY  (`DD_ID`),
  CONSTRAINT `FK_DEPARTAMENTO_DEPARTAMENTO_DEPARTAMENTO` FOREIGN KEY (`DD_DEPARTAMENTO`) REFERENCES `departamento` (`DEP_ID`),
  CONSTRAINT `FK_DEPARTAMENTO_DEPARTAMENTO_DEPARTAMENTO_DONO` FOREIGN KEY (`DD_DEPARTAMENTO_DONO`) REFERENCES `departamento` (`DEP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=latin1;

CREATE TABLE `departamento_socio` (
  `DS_ID` int(11) NOT NULL auto_increment,
  `DS_DEPARTAMENTO` int(11) NOT NULL,
  `DS_SOCIO` int(11) NOT NULL,
  `DS_PORCENTAGEM` varchar(6) NOT NULL,
  PRIMARY KEY  (`DS_ID`),
  CONSTRAINT `FK_DEPARTAMENTO_SOCIO_DEPARTAMENTO` FOREIGN KEY (`DS_DEPARTAMENTO`) REFERENCES `departamento` (`DEP_ID`),
  CONSTRAINT `FK_DEPARTAMENTO_SOCIO_SOCIO` FOREIGN KEY (`DS_SOCIO`) REFERENCES `socio` (`SOC_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;

CREATE TABLE `despesa` (
  `DES_ID` int(11) NOT NULL auto_increment,
  `DES_NOME` varchar(100) NOT NULL,
  `DES_ESTA_ATIVA` varchar(1) NOT NULL default 'S',
  `DES_EH_EXTRA` varchar(1) NOT NULL default 'S',
  `DES_CATEGORIA` int(11) NOT NULL,
  `DES_DEPARTAMENTO` int(11) NOT NULL,
  PRIMARY KEY  (`DES_ID`),
  CONSTRAINT `FK_DESPESA_CATEGORIA_DESPESA` FOREIGN KEY (`DES_CATEGORIA`) REFERENCES `categoria_despesa` (`CD_ID`),
  CONSTRAINT `FK_DESPESA_DEPARTAMENTO` FOREIGN KEY (`DES_DEPARTAMENTO`) REFERENCES `departamento` (`DEP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=176 DEFAULT CHARSET=latin1;

CREATE TABLE `despesa_por_vencimento` (
  `DPV_ID` int(11) NOT NULL auto_increment,
  `DPV_VALOR` varchar(100) NOT NULL,
  `DPV_DESPESA` int(11) NOT NULL,
  `DPV_VENCIMENTO` int(11) NOT NULL,
  `DPV_OBSERVACAO` varchar(255) default NULL,
  PRIMARY KEY  (`DPV_ID`),
  CONSTRAINT `FK_DESPESA_POR_VENCIMENTO_DESPESA` FOREIGN KEY (`DPV_DESPESA`) REFERENCES `despesa` (`DES_ID`),
  CONSTRAINT `FK_DESPESA_POR_VENCIMENTO_VENCIMENTO` FOREIGN KEY (`DPV_VENCIMENTO`) REFERENCES `vencimento` (`VEN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=990 DEFAULT CHARSET=latin1;

CREATE TABLE despesa_extra (
  DE_ID int(11) NOT NULL auto_increment,
  DE_VALOR varchar(100) NOT NULL,
  DE_DESCRICAO varchar(100) NOT NULL,
  DE_DESPESA_POR_VENCIMENTO int(11) NOT NULL,
  PRIMARY KEY  (DE_ID),
  CONSTRAINT FK_DESPESA_EXTRA_DESPESA_POR_VENCIMENTO FOREIGN KEY (DE_DESPESA_POR_VENCIMENTO) REFERENCES despesa_por_vencimento (DPV_ID)
);

CREATE TABLE `receita` (
  `REC_ID` int(11) NOT NULL auto_increment,
  `REC_QUANTIDADE_EXAMES` varchar(15) NOT NULL,
  `REC_VALOR_BRUTO` varchar(15) NOT NULL,
  `REC_DEPARTAMENTO` int(11) NOT NULL,
  `REC_RECEITA_POR_CONVENIO` int(11) NOT NULL,
  PRIMARY KEY  (`REC_ID`),
  CONSTRAINT `FK_RECEITA_DEPARTAMENTO` FOREIGN KEY (`REC_DEPARTAMENTO`) REFERENCES `departamento` (`DEP_ID`),
  CONSTRAINT `FK_RECEITA_RECEITA_POR_CONVENIO` FOREIGN KEY (`REC_RECEITA_POR_CONVENIO`) REFERENCES `receita_por_convenio` (`RPC_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=379 DEFAULT CHARSET=latin1;

CREATE TABLE `receita_por_convenio` (
  `RPC_ID` int(11) NOT NULL auto_increment,
  `RPC_DATA_DEPOSITO` varchar(15) NOT NULL,
  `RPC_QUANTIDADE_EXAMES_TOTAL` varchar(15) NOT NULL,
  `RPC_ALIQUOTA_IR` varchar(15) NOT NULL,
  `RPC_DEDUCAO_IR` varchar(15) NOT NULL,
  `RPC_VALOR_EXAMES` varchar(15) NOT NULL,
  `RPC_VALOR_MATERIAIS` varchar(15) NOT NULL,
  `RPC_VALOR_FILMES` varchar(15) NOT NULL,
  `RPC_VALOR_MEDICAMENTOS` varchar(15) NOT NULL,
  `RPC_INSS_TOTAL` varchar(15) NOT NULL,
  `RPC_IR_TOTAL` varchar(15) NOT NULL,
  `RPC_PAGAMENTO_PARTICULAR` varchar(15) NOT NULL,
  `RPC_OUTRAS_DESPESAS` varchar(15) NOT NULL,
  `RPC_VALOR_BRUTO_TOTAL` varchar(15) NOT NULL,
  `RPC_VALOR_DESPESAS_TOTAL` varchar(15) NOT NULL,
  `RPC_VALOR_CREDITADO` varchar(15) NOT NULL,
  `RPC_CONVENIO` int(11) NOT NULL,
  `RPC_VENCIMENTO` int(11) NOT NULL,
  PRIMARY KEY  (`RPC_ID`),
  CONSTRAINT `FK_RECEITA_POR_CONVENIO_CONVENIO` FOREIGN KEY (`RPC_CONVENIO`) REFERENCES `convenio` (`CON_ID`),
  CONSTRAINT `FK_RECEITA_POR_CONVENIO_VENCIMENTO` FOREIGN KEY (`RPC_VENCIMENTO`) REFERENCES `vencimento` (`VEN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=192 DEFAULT CHARSET=latin1;

CREATE TABLE `socio` (
  `SOC_ID` int(11) NOT NULL auto_increment,
  `SOC_NOME` varchar(100) NOT NULL,
  PRIMARY KEY  (`SOC_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

CREATE TABLE `usuario` (
  `USU_ID` int(11) NOT NULL auto_increment,
  `USU_LOGIN` varchar(100) NOT NULL,
  `USU_SENHA` varchar(45) NOT NULL,
  `USU_NIVEL` varchar(45) NOT NULL,
  PRIMARY KEY  (`USU_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

CREATE TABLE `vencimento` (
  `VEN_ID` int(11) NOT NULL auto_increment,
  `VEN_NOME` varchar(100) NOT NULL,
  PRIMARY KEY  (`VEN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=latin1;

CREATE TABLE `retirada` (
  `RET_ID` int(11) NOT NULL auto_increment,
  `RET_VALOR` varchar(100) NOT NULL,
  `RET_DATA` DATE NOT NULL DEFAULT CURRENT_DATE,
  `RET_SOCIO` int(11) NOT NULL,
  `RET_VENCIMENTO` int(11) NOT NULL,
  PRIMARY KEY  (`RET_ID`),
  CONSTRAINT `FK_RETIRADA_SOCIO` FOREIGN KEY (`RET_SOCIO`) REFERENCES `socio` (`SOC_ID`),
  CONSTRAINT `FK_RETIRADA_VENCIMENTO` FOREIGN KEY (`RET_VENCIMENTO`) REFERENCES `vencimento` (`VEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `aplicacao` (
  `APL_ID` int(11) NOT NULL auto_increment,
  `APL_VALOR` varchar(100) NOT NULL,
  `APL_DATA` DATE NOT NULL DEFAULT CURRENT_DATE,
  `APL_SOCIO` int(11) NOT NULL,
  `APL_DESCRICAO` varchar(255) NOT NULL,
  `APL_VENCIMENTO` int(11) NOT NULL,
  PRIMARY KEY  (`APL_ID`),
  CONSTRAINT `FK_APLICACAO_SOCIO` FOREIGN KEY (`APL_SOCIO`) REFERENCES `socio` (`SOC_ID`),
  CONSTRAINT `FK_APLICACAO_VENCIMENTO` FOREIGN KEY (`APL_VENCIMENTO`) REFERENCES `vencimento` (`VEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `receita_avulsa`;
CREATE TABLE `acm`.`receita_avulsa` (
  `RA_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `RA_NOME` VARCHAR(100) NOT NULL,
  `RA_VALOR` VARCHAR(100) NOT NULL,
  `RA_VENCIMENTO` INT(11) NOT NULL,
  PRIMARY KEY (`RA_ID`),
  CONSTRAINT `FK_receita_avulsa_vencimento` FOREIGN KEY `FK_receita_avulsa_vencimento` (`RA_VENCIMENTO`)
    REFERENCES `vencimento` (`VEN_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `acm`.`receita_avulsa_socio`;
CREATE TABLE  `acm`.`receita_avulsa_socio` (
  `RAS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RAS_RECEITA_AVULSA` int(11) NOT NULL,
  `RAS_SOCIO` int(11) NOT NULL,
  PRIMARY KEY (`RAS_ID`),
  CONSTRAINT `FK_receita_avulsa_socio_receita_avulsa` FOREIGN KEY `FK_receita_avulsa_socio_receita_avulsa` (`RAS_RECEITA_AVULSA`)
    REFERENCES `receita_avulsa` (`RA_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_receita_avulsa_socio_socio` FOREIGN KEY `FK_receita_avulsa_socio_socio` (`RAS_SOCIO`)
    REFERENCES `socio` (`SOC_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
) ENGINE=InnoDB;

ALTER TABLE CATEGORIA_DESPESA ADD UNIQUE (CD_NOME);
ALTER TABLE CONTA_PAGAMENTO ADD UNIQUE (CP_NOME, CP_BANCO);
ALTER TABLE CONVENIO ADD UNIQUE (CON_NOME);
ALTER TABLE DEPARTAMENTO ADD UNIQUE (DEP_NOME);
ALTER TABLE DEPARTAMENTO_DEPARTAMENTO ADD UNIQUE (DD_DEPARTAMENTO, DD_DEPARTAMENTO_DONO);
ALTER TABLE DEPARTAMENTO_SOCIO ADD UNIQUE (DS_DEPARTAMENTO, DS_SOCIO);
ALTER TABLE DESPESA ADD UNIQUE (DES_NOME);
ALTER TABLE DESPESA_POR_VENCIMENTO ADD UNIQUE (DPV_DESPESA, DPV_VENCIMENTO);
ALTER TABLE RECEITA ADD UNIQUE (REC_RECEITA_POR_CONVENIO, REC_DEPARTAMENTO);
ALTER TABLE RECEITA_POR_CONVENIO ADD UNIQUE (RPC_VENCIMENTO, RPC_CONVENIO);
ALTER TABLE SOCIO ADD UNIQUE (SOC_NOME);
ALTER TABLE USUARIO ADD UNIQUE (USU_LOGIN);
ALTER TABLE VENCIMENTO ADD UNIQUE (VEN_NOME);