DELIMITER $$

DROP FUNCTION IF EXISTS `GETVALORLIQUIDORECEITA` $$
CREATE FUNCTION `GETVALORLIQUIDORECEITA`(RECEITA INTEGER) RETURNS decimal(10,2)
BEGIN
    RETURN (SELECT  CONVERTERVARCHAREMDECIMAL(REC.REC_VALOR_BRUTO)
                    -
                    (
                      (
                            CONVERTERVARCHAREMDECIMAL(RPC.RPC_INSS_TOTAL)
                            +
                            CONVERTERVARCHAREMDECIMAL(RPC.RPC_IR_TOTAL)
                            +
                            CONVERTERVARCHAREMDECIMAL(RPC.RPC_OUTRAS_DESPESAS)
                      )
                      *
                      (REC.REC_QUANTIDADE_EXAMES / RPC.RPC_QUANTIDADE_EXAMES_TOTAL)
                    )
            FROM RECEITA REC JOIN RECEITA_POR_CONVENIO RPC ON REC.REC_RECEITA_POR_CONVENIO = RPC.RPC_ID
            WHERE REC.REC_ID = RECEITA
           );
END $$

DROP FUNCTION IF EXISTS `GETPORCENTAGEMNOVAESTRUTURA` $$
CREATE FUNCTION `GETPORCENTAGEMNOVAESTRUTURA`(ID_DEP_DONO INTEGER, ID_DEP INTEGER) RETURNS decimal(10,2)
BEGIN
    RETURN IF(ID_DEP_DONO = 1 OR ID_DEP_DONO = 2, IF(ID_DEP = 3, 50.0, IF(ID_DEP = 9, 49.0, 0)),
             IF(ID_DEP_DONO = 3, IF(ID_DEP = 1 OR ID_DEP = 2, 100.0,IF(ID_DEP = 9, 98.0, 0)),
                IF(ID_DEP_DONO = 4, IF(ID_DEP = 5 OR ID_DEP = 6, 100.0,IF(ID_DEP = 9, 0, 0)),
                   IF(ID_DEP_DONO = 5 OR ID_DEP_DONO = 6, IF(ID_DEP = 4, 50.0, IF(ID_DEP = 9, 0.0, 0)),
                      IF(ID_DEP_DONO = 7, IF(ID_DEP = 10 OR ID_DEP = 11, 100.0,IF(ID_DEP = 9, 2.0, 0)),
                         IF(ID_DEP_DONO = 10 OR ID_DEP_DONO = 11, IF(ID_DEP = 7, 50.0, IF(ID_DEP = 9, 1.0, 0)),
                              IF(ID_DEP_DONO = 9, 100.0,0)
                         )
                      )
                   )
                )
             )
           );
END $$

DROP FUNCTION IF EXISTS `GETPORCENTAGEMESTRUTURAANTIGA` $$
CREATE FUNCTION `GETPORCENTAGEMESTRUTURAANTIGA`(ID_DEP_DONO INTEGER, ID_DEP INTEGER) RETURNS decimal(10,2)
BEGIN
    RETURN IF(ID_DEP_DONO = 1 OR ID_DEP_DONO = 2, IF(ID_DEP = 3, 50.0, IF(ID_DEP = 9, 33.0, 0)),
             IF(ID_DEP_DONO = 3, IF(ID_DEP = 1 OR ID_DEP = 2, 100.0,IF(ID_DEP = 9, 66.0, 0)),
                IF(ID_DEP_DONO = 4, IF(ID_DEP = 5 OR ID_DEP = 6, 100.0,IF(ID_DEP = 9, 32, 0)),
                   IF(ID_DEP_DONO = 5 OR ID_DEP_DONO = 6, IF(ID_DEP = 4, 50.0, IF(ID_DEP = 9, 16.0, 0)),
                      IF(ID_DEP_DONO = 7, IF(ID_DEP = 10 OR ID_DEP = 11, 100.0,IF(ID_DEP = 9, 2.0, 0)),
                         IF(ID_DEP_DONO = 10 OR ID_DEP_DONO = 11, IF(ID_DEP = 7, 50.0, IF(ID_DEP = 9, 1.0, 0)),
                              IF(ID_DEP_DONO = 9, 100.0,0)
                         )
                      )
                   )
                )
             )
           );
END $$

DROP FUNCTION IF EXISTS `GETDEPARTAMENTOSINDIRETOSESTRUTURAANTIGA` $$
CREATE FUNCTION `GETDEPARTAMENTOSINDIRETOSESTRUTURAANTIGA`(ID_DEP INTEGER) RETURNS varchar(100) CHARSET latin1
BEGIN
    RETURN IF(ID_DEP = 1 OR ID_DEP = 2, ",3,9,",
             IF(ID_DEP = 3, ",1,2,9,",
                IF(ID_DEP = 4, ",5,6,9,",
                   IF(ID_DEP = 5 OR ID_DEP = 6, ",4,9,",
                      IF(ID_DEP = 7, ",10,11,9,",
                         IF(ID_DEP = 10 OR ID_DEP = 11, ",7,9,",
                              IF(ID_DEP = 9, ",1,2,3,4,5,6,7,10,11,","")
                         )
                      )
                   )
                )
             )
           );
END $$

DROP FUNCTION IF EXISTS `GETDEPARTAMENTOSINDIRETOSNOVAESTRUTURA` $$
CREATE FUNCTION `GETDEPARTAMENTOSINDIRETOSNOVAESTRUTURA`(ID_DEP INTEGER) RETURNS varchar(100) CHARSET latin1
BEGIN
    RETURN IF(ID_DEP = 1 OR ID_DEP = 2, ",3,9,",
             IF(ID_DEP = 3, ",1,2,9,",
                IF(ID_DEP = 4, ",5,6,",
                   IF(ID_DEP = 5 OR ID_DEP = 6, ",4,",
                      IF(ID_DEP = 7, ",10,11,9,",
                         IF(ID_DEP = 10 OR ID_DEP = 11, ",7,9,",
                              IF(ID_DEP = 9, ",1,2,3,4,5,6,7,10,11,","")
                         )
                      )
                   )
                )
             )
           );
END $$

DROP FUNCTION IF EXISTS `GETPORCENTAGEMDEPARTAMENTOSINDIRETOS` $$
CREATE FUNCTION `GETPORCENTAGEMDEPARTAMENTOSINDIRETOS`(ID_DEP_DONO INTEGER, ID_DEP INTEGER, VENCIMENTO VARCHAR(7)) RETURNS decimal(10,2)
BEGIN
    RETURN IF(VENCIMENTO < "2014/10", GETPORCENTAGEMESTRUTURAANTIGA(ID_DEP_DONO, ID_DEP) , GETPORCENTAGEMNOVAESTRUTURA(ID_DEP_DONO, ID_DEP));
END $$

DROP FUNCTION IF EXISTS `GETDEPARTAMENTOSINDIRETOS` $$
CREATE FUNCTION `GETDEPARTAMENTOSINDIRETOS`(ID_DEP INTEGER, VENCIMENTO VARCHAR(7)) RETURNS varchar(100) CHARSET latin1
BEGIN
    RETURN IF(VENCIMENTO < "2014/10", GETDEPARTAMENTOSINDIRETOSESTRUTURAANTIGA(ID_DEP) , GETDEPARTAMENTOSINDIRETOSNOVAESTRUTURA(ID_DEP));
END $$

DROP FUNCTION IF EXISTS `GETDESPESASINDIRETASPORVENCIMENTOESOCIA` $$
CREATE FUNCTION `GETDESPESASINDIRETASPORVENCIMENTOESOCIA`(VENCIMENTO VARCHAR(7), SOCIA INTEGER) RETURNS decimal(10,2)
BEGIN
  RETURN (SELECT SUM(
                    ROUND((
                          IF(CONVERTERVARCHAREMDECIMAL(DPV.DPV_VALOR) IS NULL, 0, CONVERTERVARCHAREMDECIMAL(DPV.DPV_VALOR))
                          *
                          (GETPORCENTAGEMDEPARTAMENTOSINDIRETOS(DEP.DEP_ID, DES.DES_DEPARTAMENTO, V.VEN_NOME) / 100)
                    ), 2)
                )
         FROM DESPESA_POR_VENCIMENTO DPV JOIN VENCIMENTO V ON DPV.DPV_VENCIMENTO = V.VEN_ID, DEPARTAMENTO DEP, DESPESA DES, SOCIO SOC, DEPARTAMENTO_SOCIO DS
         WHERE V.VEN_NOME LIKE VENCIMENTO AND DES.DES_ID = DPV.DPV_DESPESA
               AND DS.DS_DEPARTAMENTO = DEP.DEP_ID AND DS.DS_SOCIO = SOC.SOC_ID AND (GETDEPARTAMENTOSINDIRETOS(DEP.DEP_ID, V.VEN_NOME) LIKE concat("%,",DES.DES_DEPARTAMENTO,",%"))
               AND SOC.SOC_ID= SOCIA);
END $$

DROP FUNCTION IF EXISTS `GETDESPESASPORANOESOCIA` $$
CREATE FUNCTION `GETDESPESASPORANOESOCIA`(ANO VARCHAR(4), SOCIA INTEGER) RETURNS decimal(10,2)
BEGIN
  RETURN GETDESPESASDIRETASPORVENCIMENTOESOCIA(CONCAT(ANO, '___'), SOCIA) + GETDESPESASINDIRETASPORVENCIMENTOESOCIA(CONCAT(ANO, '___'), SOCIA);
END $$

DROP FUNCTION IF EXISTS `GETRECEITASINDIRETASPORVENCIMENTOESOCIA` $$
CREATE FUNCTION `GETRECEITASINDIRETASPORVENCIMENTOESOCIA`(VENCIMENTO VARCHAR(7), SOCIA INTEGER) RETURNS decimal(10,2)
BEGIN
  RETURN (SELECT SUM(
                    ROUND((
                          IF(GETVALORLIQUIDORECEITA(REC.REC_ID) IS NULL, 0, GETVALORLIQUIDORECEITA(REC.REC_ID))
                          *
                          (GETPORCENTAGEMDEPARTAMENTOSINDIRETOS(DEP.DEP_ID, REC.REC_DEPARTAMENTO, V.VEN_NOME) / 100)
                          ), 2)
                )
         FROM RECEITA_POR_CONVENIO RPC JOIN VENCIMENTO V ON RPC.RPC_VENCIMENTO = V.VEN_ID, DEPARTAMENTO DEP, RECEITA REC, SOCIO SOC, DEPARTAMENTO_SOCIO DS
         WHERE V.VEN_NOME LIKE VENCIMENTO AND REC.REC_RECEITA_POR_CONVENIO = RPC.RPC_ID
               AND DS.DS_DEPARTAMENTO = DEP.DEP_ID  AND DS.DS_SOCIO = SOC.SOC_ID AND (GETDEPARTAMENTOSINDIRETOS(DEP.DEP_ID, V.VEN_NOME) LIKE concat("%,",REC.REC_DEPARTAMENTO,",%"))
               AND SOC.SOC_ID = SOCIA);
END $$

DROP FUNCTION IF EXISTS `GETRECEITASPORANOESOCIA` $$
CREATE FUNCTION `GETRECEITASPORANOESOCIA`(ANO VARCHAR(4), SOCIA INTEGER) RETURNS decimal(10,2)
BEGIN
  RETURN GETRECEITASDIRETASPORVENCIMENTOESOCIA(CONCAT(ANO, '___'), SOCIA) + GETRECEITASINDIRETASPORVENCIMENTOESOCIA(CONCAT(ANO, '___'), SOCIA);
END $$	

DELIMITER ;