CREATE TABLE IF NOT EXISTS RESGATE (
  `RES_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RES_VALOR` varchar(100) NOT NULL,
  `RES_DATA` date NOT NULL,
  `RES_SOCIO` int(11) NOT NULL,
  `RES_DESCRICAO` varchar(255) NOT NULL,
  `RES_VENCIMENTO` int(11) NOT NULL,
  PRIMARY KEY (`RES_ID`)
) ENGINE = InnoDB AUTO_INCREMENT=1;